name: Update last updated

on:
  push:
    branches:
      - main

jobs:
  update-last-updated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm install
      - name: Update last updated
        env:
          READ_COMMIT_TOKEN: ${{ secrets.READ_COMMIT_TOKEN }}
        run: |
          node update-last-updated.js $READ_COMMIT_TOKEN
        working-directory: "./scripts"
